const ROLES = {
  OWNER: 'owner',
  STAFF: 'staff',
  CLIENT: 'client',
  ADMIN: 'admin',
} as const;

const ORDER_STATUSES = {
  QUEUED: 'queued',
  ASSIGNED: 'assigned',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  NO_SHOW: 'no_show',
  CANCELLED: 'cancelled',
} as const;

const VALID_STATUS_TRANSITIONS: Record<string, string[]> = {
  [ORDER_STATUSES.QUEUED]: [ORDER_STATUSES.ASSIGNED, ORDER_STATUSES.CANCELLED, ORDER_STATUSES.NO_SHOW],
  [ORDER_STATUSES.ASSIGNED]: [ORDER_STATUSES.IN_PROGRESS, ORDER_STATUSES.CANCELLED, ORDER_STATUSES.NO_SHOW],
  [ORDER_STATUSES.IN_PROGRESS]: [ORDER_STATUSES.COMPLETED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.COMPLETED]: [],
  [ORDER_STATUSES.NO_SHOW]: [],
  [ORDER_STATUSES.CANCELLED]: [],
};

const ACTIVE_ORDER_STATUSES: string[] = [
  ORDER_STATUSES.QUEUED,
  ORDER_STATUSES.ASSIGNED,
  ORDER_STATUSES.IN_PROGRESS,
];

const PAYMENT_METHODS = ['cash', 'card', 'transfer'] as const;

// Mijoz kelmasa, rejalashtirilgan vaqtdan shuncha daqiqa o'tgach no_show qilinadi
const NO_SHOW_MINUTES = 20;

const PAGE_SIZE = 20;

export { ROLES, ORDER_STATUSES, VALID_STATUS_TRANSITIONS, ACTIVE_ORDER_STATUSES, PAYMENT_METHODS, NO_SHOW_MINUTES, PAGE_SIZE };
