const ROLES = {
  CLIENT: 'client',
  MASTER: 'master',
  SELLER: 'seller',
  ADMIN: 'admin',
} as const;

const ORDER_STATUSES = {
  NEW: 'new',
  ACCEPTED: 'accepted',
  COMING: 'coming',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
} as const;

const VALID_STATUS_TRANSITIONS: Record<string, string[]> = {
  [ORDER_STATUSES.ACCEPTED]: [ORDER_STATUSES.COMING, ORDER_STATUSES.FAILED],
  [ORDER_STATUSES.COMING]: [ORDER_STATUSES.IN_PROGRESS, ORDER_STATUSES.FAILED],
  [ORDER_STATUSES.IN_PROGRESS]: [ORDER_STATUSES.COMPLETED, ORDER_STATUSES.FAILED],
};

const MASTER_CONSTANTS = {
  ORDER_ACCEPT_PRICE: 4999,
  INITIAL_BALANCE: 100000,
};

const PAGE_SIZE = 20;

export { ROLES, ORDER_STATUSES, VALID_STATUS_TRANSITIONS, MASTER_CONSTANTS, PAGE_SIZE };
