const ROLES = {
  CLIENT: 'client',
  MASTER: 'master',
  SELLER: 'seller',
  ADMIN: 'admin',
};

const ORDER_STATUSES = {
  NEW: 'new',
  ACCEPTED: 'accepted',
  COMING: 'coming',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
};

const VALID_STATUS_TRANSITIONS = {
  [ORDER_STATUSES.ACCEPTED]: [ORDER_STATUSES.COMING],
  [ORDER_STATUSES.COMING]: [ORDER_STATUSES.IN_PROGRESS],
  [ORDER_STATUSES.IN_PROGRESS]: [ORDER_STATUSES.COMPLETED, ORDER_STATUSES.FAILED],
};

const MASTER_CONSTANTS = {
  ORDER_ACCEPT_PRICE: 4999,
  INITIAL_BALANCE: 100000,
};

const PAGE_SIZE = 20;

module.exports = {
  ROLES,
  ORDER_STATUSES,
  VALID_STATUS_TRANSITIONS,
  MASTER_CONSTANTS,
  PAGE_SIZE,
};
